# Generated by Django 6.0 on 2026-01-31 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GOVERNMENT', 'Government Entity'), ('COMPANY', 'Company')], max_length=20)),
                ('role', models.CharField(choices=[('PLAINTIFF', 'Plaintiff'), ('DEFENDANT', 'Defendant')], max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProceduralRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('parameter_value', models.JSONField(help_text="Dynamic parameters for the rule (e.g., {'days': 60})")),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(help_text='Date when the incident happened or right was denied')),
                ('grievance_date', models.DateField(blank=True, help_text='Date of complaint to the entity', null=True)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('court_type', models.CharField(help_text='e.g., General, Administrative, Commercial', max_length=100)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VALIDATED', 'Validated'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('documents', models.JSONField(default=list, help_text='List of attached document metadata')),
                ('defendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_as_defendant', to='legal_engine.party')),
                ('plaintiff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases_as_plaintiff', to='legal_engine.party')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField()),
                ('rejection_reasons', models.JSONField(default=list, help_text='List of procedural errors if any')),
                ('ai_analysis', models.TextField(help_text="Gemini's analysis of the legal text")),
                ('generated_reasoning', models.TextField(help_text='The eloquent reasoning generated for the judge')),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validation_result', to='legal_engine.case')),
            ],
        ),
    ]
