# Generated by Django 6.0 on 2026-02-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='request_type',
            field=models.CharField(choices=[('ADMINISTRATIVE_DECISION', 'Challenging an administrative decision'), ('COMPENSATION', 'Claim for compensation')], default='ADMINISTRATIVE_DECISION', help_text='Type of request: Decision Challenge or Compensation', max_length=50),
        ),
    ]
